#include <cassert>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <memory>
#include <sstream>
#include <string>
#include <vector>
#include <utility>

#include <cuda_runtime.h>

#include "AC/Core/Image.hpp"
#include "AC/Core/Model.hpp"
#include "AC/Core/Processor.hpp"
#include "AC/Core/Util.hpp"
#include "AC/Util/ThreadLocal.hpp"

#include "AC/Core/Internal/Processor/CUDA/Common.hpp"

#include "ACCoreExport.hpp" // Generated by CMake

#define ContextList (ac::core::cuda::getContextList())

namespace ac::core::cuda
{
    struct Context
    {
        std::string name{};
        int id{};
        int vram{};
        int computeCapability{};
        int performanceScore{};
        bool memoryPoolsSupported{};

        Context() noexcept = default;
        Context(const int deviceId, const cudaDeviceProp& deviceProp) noexcept
        {
            name = deviceProp.name;
            id = deviceId;
            vram = static_cast<int>(deviceProp.totalGlobalMem >> 20);
            computeCapability = deviceProp.major * 10 + deviceProp.minor;
            memoryPoolsSupported = deviceProp.memoryPoolsSupported;

            int clockRate = 0;
            cudaDeviceGetAttribute(&clockRate, cudaDevAttrClockRate, deviceId);
            int multiProcessorCount = 0;
            cudaDeviceGetAttribute(&multiProcessorCount, cudaDevAttrMultiProcessorCount, deviceId);

            performanceScore = clockRate * multiProcessorCount;
        }
    };

    static inline bool checkDevice(const int deviceId, const cudaDeviceProp& deviceProp)
    {
        cudaError_t err = cudaSuccess;

        if (deviceProp.major < 5) return false;

        int computeMode = cudaComputeModeDefault;
        err = cudaDeviceGetAttribute(&computeMode, cudaDevAttrComputeMode, deviceId);
        if (err != cudaSuccess || computeMode == cudaComputeModeProhibited) return false;

        return true;
    }

    //lazy load, god knows if it's safe to call the cuda function during DLL initialization
    static inline std::vector<Context>& getContextList() noexcept
    {
        static auto contextList = []() -> std::vector<Context> {
            int deviceCount = 0;
            auto err = cudaGetDeviceCount(&deviceCount); if (err != cudaSuccess) return {};
            std::vector<Context> contexts{};
            for (int i = 0; i < deviceCount; i++)
            {
                cudaDeviceProp deviceProp{};
                err = cudaGetDeviceProperties(&deviceProp, i); if (err != cudaSuccess) continue;
                if (checkDevice(i, deviceProp)) contexts.emplace_back(i, deviceProp);
            }
            return contexts;
        }();
        return contextList;
    }

    static inline cudaError_t copyImageHostToDevice(DeviceImage& dst, const Image& src, const cudaStream_t stream) noexcept
    {
        auto lineSize = src.width() * src.pixelSize();
        return cudaMemcpy2DAsync(dst.ptr(), dst.stride(), src.ptr(), src.stride(), lineSize, src.height(), cudaMemcpyHostToDevice, stream);
    }
    static inline cudaError_t copyImageDeviceToHost(Image& dst, const DeviceImage& src, const cudaStream_t stream) noexcept
    {
        auto lineSize = src.width() * src.pixelSize();
        return cudaMemcpy2DAsync(dst.ptr(), dst.stride(), src.ptr(), src.stride(), lineSize, src.height(), cudaMemcpyDeviceToHost, stream);
    }

    class DeviceAllocator
    {
    public:
        cudaError_t init(const Context& ctx) noexcept
        {
            cudaError_t err = cudaSuccess;

            deviceId = ctx.id;
            memoryPoolsSupported = ctx.memoryPoolsSupported;
            if (memoryPoolsSupported)
            {
                deviceMalloc = deviceMallocAsync;
                deviceFree = deviceFreeAsync;

                cudaMemPool_t pool{};
                err = cudaDeviceGetDefaultMemPool(&pool, deviceId);
                if (err == cudaSuccess)
                {
                    auto threshold = std::numeric_limits<std::uint64_t>::max();
                    err = cudaMemPoolSetAttribute(pool, cudaMemPoolAttrReleaseThreshold, &threshold);
                }
            }
            else
            {
                deviceMalloc = deviceMallocSync;
                deviceFree = deviceFreeSync;
            }

            return err;
        }
        cudaError_t deinit() const noexcept
        {
            cudaError_t err = cudaSuccess;

            if (memoryPoolsSupported)
            {
                cudaMemPool_t pool{};
                err = cudaDeviceGetDefaultMemPool(&pool, deviceId);
                if (err == cudaSuccess) err = cudaMemPoolTrimTo(pool, 0);
            }

            return err;
        }

        cudaError_t allocate(void** const devPtr, const std::size_t size, const cudaStream_t stream) const noexcept
        {
            return deviceMalloc(devPtr, size, stream);
        }
        cudaError_t deallocate(void** const devPtr, const cudaStream_t stream) const noexcept
        {
            auto err = cudaSuccess;
            if (devPtr && *devPtr)
            {
                err = deviceFree(*devPtr, stream);
                if (err == cudaSuccess) *devPtr = nullptr;
            }
            return err;
        }

    private:
        static cudaError_t deviceMallocAsync(void** const devPtr, const std::size_t size, const cudaStream_t stream) noexcept
        {
            return cudaMallocAsync(devPtr, size, stream);
        }
        static cudaError_t deviceFreeAsync(void* const devPtr, const cudaStream_t stream) noexcept
        {
            return cudaFreeAsync(devPtr, stream);
        }
        static cudaError_t deviceMallocSync(void** const devPtr, const std::size_t size, const cudaStream_t /*stream*/) noexcept
        {
            return cudaMalloc(devPtr, size);
        }
        static cudaError_t deviceFreeSync(void* const devPtr, const cudaStream_t /*stream*/) noexcept
        {
            return cudaFree(devPtr);
        }

    private:
        decltype(&deviceMallocAsync) deviceMalloc = deviceMallocSync;
        decltype(&deviceFreeAsync) deviceFree = deviceFreeSync;
        int deviceId = 0;
        bool memoryPoolsSupported = false;
    };

    class ImageBuffer : private DeviceImage
    {
    public:
        ImageBuffer(const DeviceAllocator& allocator, const cudaStream_t stream) noexcept : allocator(allocator), stream(stream) {}
        ImageBuffer(const ImageBuffer&) = delete;
        ImageBuffer(ImageBuffer&&) = delete;
        ImageBuffer& operator=(const ImageBuffer&) = delete;
        ImageBuffer& operator=(ImageBuffer&&) = delete;
        ~ImageBuffer() noexcept
        {
            if (pixels)
            {   // There should not be any errors here.
                auto err = allocator.deallocate(&this->pixels, stream);
                assert(err == cudaSuccess);
            }
        }

        DeviceImage& get(
            const int width,
            const int height,
            const int channels,
            const ElementType elementType,
            cudaError_t& err) noexcept
        {
            if (!this->pixels || this->width() != width || this->height() != height || this->type() != elementType)
            {
                if (this->pixels)
                {
                    err = allocator.deallocate(&this->pixels, stream);
                    if (err != cudaSuccess) return *this;
                }
                // update shapes
                this->w = width;
                this->h = height;
                this->c = channels;
                this->elementType = elementType;
                this->pitch = align(this->width() * this->pixelSize(), 128);

                err = allocator.allocate(&this->pixels, this->size(), stream);
                if (err != cudaSuccess) this->pixels = nullptr;
            }

            return *this;
        }

    private:
        cudaStream_t stream;
        DeviceAllocator allocator;
    };

    class CUDAProcessorBase : public Processor
    {
    public:
        CUDAProcessorBase(const int device) noexcept
        {
            auto& err = errors.local();
            if (ContextList.empty()) err = cudaErrorNoDevice;
            else
            {
                int deviceCount = static_cast<int>(ContextList.size());
                if (!(device >= 0 && device < deviceCount))
                {
                    idx = 0;
                    for (int i = 0; i < deviceCount; i++)
                        if (ContextList[i].performanceScore > ContextList[idx].performanceScore)
                            idx = i;
                }
                else idx = device;
                context = ContextList[idx];
                err = allocator.init(context);
            }
        };
        ~CUDAProcessorBase() noexcept override
        {
            // there should not be any error here, we tentatively keep 'err' to avoid ignoring the return value.
            auto& err = errors.local();
            err = allocator.deinit();
            assert(err == cudaSuccess);
        }

        bool ok() noexcept override
        {
            return errors.local() == cudaSuccess;
        }
        const char* error() noexcept override
        {
            return cudaGetErrorString(errors.local());
        }
        const char* name() const noexcept override
        {
            return context.name.c_str();
        }
        int type() const noexcept override
        {
            return Processor::CUDA;
        }
        const char* typeName() const noexcept override
        {
            return "CUDA";
        }

    protected:
        Context context{};
        DeviceAllocator allocator{};
        util::ThreadLocal<cudaError_t> errors{};
    };

    template<typename Model>
    class CUDAProcessorSeqCNN : public CUDAProcessorBase
    {
    public:
        CUDAProcessorSeqCNN(const int device, const Model& model) noexcept : CUDAProcessorBase(device), model(model)
        {
            auto& err = errors.local(); if (err != cudaSuccess) return;
            err = cudaSetDevice(idx); if (err != cudaSuccess) return;

            for (int i = 0; i < model.kernels(); i++)
            {
                int layer = model.kernelLayer(i);
                float* dptr = nullptr;
                auto hptr = model.kernel(layer);
                auto size = model.kernelSize(layer);
                err = cudaMalloc(&dptr, size); if (err != cudaSuccess) return;
                kernels.emplace_back(dptr);
                err = cudaMemcpy(dptr, hptr, size, cudaMemcpyHostToDevice); if (err != cudaSuccess) return;
            }
            for (int i = 0; i < model.biases(); i++)
            {
                int layer = model.biasLayer(i);
                float* dptr = nullptr;
                auto hptr = model.bias(layer);
                auto size = model.biasSize(layer);
                err = cudaMalloc(&dptr, size); if (err != cudaSuccess) return;
                biases.emplace_back(dptr);
                err = cudaMemcpy(dptr, hptr, size, cudaMemcpyHostToDevice); if (err != cudaSuccess) return;
            }
            for (int i = 0; i < model.alphas(); i++)
            {
                int layer = model.alphaLayer(i);
                float* dptr = nullptr;
                auto hptr = model.alpha(layer);
                auto size = model.alphaSize(layer);
                err = cudaMalloc(&dptr, size); if (err != cudaSuccess) return;
                alphas.emplace_back(dptr);
                err = cudaMemcpy(dptr, hptr, size, cudaMemcpyHostToDevice); if (err != cudaSuccess) return;
            }
        }
        ~CUDAProcessorSeqCNN() noexcept override
        {
            // there should not be any error here, we tentatively keep 'err' to avoid ignoring the return value.
            auto& err = errors.local();
            err = cudaSetDevice(idx);

            for(auto kernel : kernels) err = cudaFree(kernel);
            for(auto bias : biases) err = cudaFree(bias);
            for(auto alpha : alphas) err = cudaFree(alpha);
        }

    protected:
        const float* kernel(const int l) const noexcept
        {
            return kernels[model.kernelIndex(l)];
        }
        const float* bias(const int l) const noexcept
        {
            return biases[model.biasIndex(l)];
        }
        const float* alpha(const int l) const noexcept
        {
            return alphas[model.alphaIndex(l)];
        }

    protected:
        Model model;
        std::vector<float*> kernels{};
        std::vector<float*> biases{};
        std::vector<float*> alphas{};
    };

    template<typename Model>
    class CUDAProcessor;
}

template<>
class ac::core::cuda::CUDAProcessor<ac::core::model::ACNetLegacy> : public CUDAProcessorSeqCNN<model::ACNetLegacy>
{
public:
    CUDAProcessor(int device, const model::ACNetLegacy& model) noexcept;
    ~CUDAProcessor() noexcept override;

private:
    void process(const Image& src, Image& dst) override;

private:
    util::ThreadLocal<ImageBuffer> inImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp1ImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp2ImageBuffers{};
    util::ThreadLocal<ImageBuffer> outImageBuffers{};
};

ac::core::cuda::CUDAProcessor<ac::core::model::ACNetLegacy>::CUDAProcessor(const int device, const model::ACNetLegacy& model) noexcept : CUDAProcessorSeqCNN(device, model) {}
ac::core::cuda::CUDAProcessor<ac::core::model::ACNetLegacy>::~CUDAProcessor() noexcept = default;

void ac::core::cuda::CUDAProcessor<ac::core::model::ACNetLegacy>::process(const Image& src, Image& dst)
{
    auto& err = errors.local();
    auto stream = cudaStreamPerThread;

    err = cudaSetDevice(idx); if (err != cudaSuccess) return;

    auto& inImageBuffer = inImageBuffers.local(allocator, stream);
    auto& tmp1ImageBuffer = tmp1ImageBuffers.local(allocator, stream);
    auto& tmp2ImageBuffer = tmp2ImageBuffers.local(allocator, stream);
    auto& outImageBuffer = outImageBuffers.local(allocator, stream);

    auto& in = inImageBuffer.get(src.width(), src.height(), src.channels(), src.type(), err); if (err != cudaSuccess) return;
    auto& tmp1 = tmp1ImageBuffer.get(src.width(), src.height(), 8, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& tmp2 = tmp2ImageBuffer.get(src.width(), src.height(), 8, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& out = outImageBuffer.get(dst.width(), dst.height(), dst.channels(), dst.type(), err); if (err != cudaSuccess) return;

    auto tmpI = &tmp2;
    auto tmpO = &tmp1;
    int l = 0;

    err = copyImageHostToDevice(in, src, stream); if (err != cudaSuccess) return;

    conv3x3_1to8_relu_cuda(in, *tmpO, kernel(l), bias(l), stream); l++;
    std::swap(tmpI, tmpO);
    for (int i = 0; i < 7; i++)
    {
        conv3x3_8to8_relu_cuda(*tmpI, *tmpO,  kernel(l), bias(l), stream); l++;
        std::swap(tmpI, tmpO);
    }
    conv3x3_8to8_relu_deconv2x2_8to1_cuda(*tmpI, out, kernel(l), bias(l), kernel(l + 1), stream);

    err = cudaPeekAtLastError(); if (err != cudaSuccess) return; // check any launch error.

    err = copyImageDeviceToHost(dst, out, stream); if (err != cudaSuccess) return;

    err = cudaStreamSynchronize(stream); if (err != cudaSuccess) return;

    err = cudaPeekAtLastError();
}

template<>
AC_CORE_EXPORT std::shared_ptr<ac::core::Processor> ac::core::Processor::create<ac::core::Processor::CUDA, ac::core::model::ACNetLegacy>(const int idx, const model::ACNetLegacy& model)
{
    return std::make_shared<cuda::CUDAProcessor<model::ACNetLegacy>>(idx, model);
}


template<>
class ac::core::cuda::CUDAProcessor<ac::core::model::ACNet<8>> : public CUDAProcessorSeqCNN<model::ACNet<8>>
{
public:
    CUDAProcessor(int device, const model::ACNet<8>& model) noexcept;
    ~CUDAProcessor() noexcept override;

private:
    void process(const Image& src, Image& dst) override;

private:
    util::ThreadLocal<ImageBuffer> inImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp1ImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp2ImageBuffers{};
    util::ThreadLocal<ImageBuffer> outImageBuffers{};
};

ac::core::cuda::CUDAProcessor<ac::core::model::ACNet<8>>::CUDAProcessor(const int device, const model::ACNet<8>& model) noexcept : CUDAProcessorSeqCNN(device, model) {}
ac::core::cuda::CUDAProcessor<ac::core::model::ACNet<8>>::~CUDAProcessor() noexcept = default;

void ac::core::cuda::CUDAProcessor<ac::core::model::ACNet<8>>::process(const Image& src, Image& dst)
{
    auto& err = errors.local();
    auto stream = cudaStreamPerThread;

    err = cudaSetDevice(idx); if (err != cudaSuccess) return;

    auto& inImageBuffer = inImageBuffers.local(allocator, stream);
    auto& tmp1ImageBuffer = tmp1ImageBuffers.local(allocator, stream);
    auto& tmp2ImageBuffer = tmp2ImageBuffers.local(allocator, stream);
    auto& outImageBuffer = outImageBuffers.local(allocator, stream);

    auto& in = inImageBuffer.get(src.width(), src.height(), src.channels(), src.type(), err); if (err != cudaSuccess) return;
    auto& tmp1 = tmp1ImageBuffer.get(src.width(), src.height(), 8, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& tmp2 = tmp2ImageBuffer.get(src.width(), src.height(), 8, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& out = outImageBuffer.get(dst.width(), dst.height(), dst.channels(), dst.type(), err); if (err != cudaSuccess) return;

    auto tmpI = &tmp2;
    auto tmpO = &tmp1;
    int l = 0;

    err = copyImageHostToDevice(in, src, stream); if (err != cudaSuccess) return;

    conv3x3_1to8_prelu_cuda(in, *tmpO, kernel(l), bias(l), alpha(l), stream); l++;
    std::swap(tmpI, tmpO);
    for (int i = 0; i < model.blocks(); i++)
    {
        conv3x3_8to8_prelu_cuda(*tmpI, *tmpO, kernel(l), bias(l), alpha(l), stream); l++;
        std::swap(tmpI, tmpO);
    }
    conv3x3_8to4_identity_pixelshuffle_4to1_add_cuda(*tmpI, out, kernel(l), bias(l), in, stream);

    err = cudaPeekAtLastError(); if (err != cudaSuccess) return; // check any launch error.

    err = copyImageDeviceToHost(dst, out, stream); if (err != cudaSuccess) return;

    err = cudaStreamSynchronize(stream); if (err != cudaSuccess) return;

    err = cudaPeekAtLastError();
}

template<>
AC_CORE_EXPORT std::shared_ptr<ac::core::Processor> ac::core::Processor::create<ac::core::Processor::CUDA, ac::core::model::ACNet<8>>(const int idx, const model::ACNet<8>& model)
{
    return std::make_shared<cuda::CUDAProcessor<model::ACNet<8>>>(idx, model);
}


template<>
class ac::core::cuda::CUDAProcessor<ac::core::model::ARNet<8>> : public CUDAProcessorSeqCNN<model::ARNet<8>>
{
public:
    CUDAProcessor(int device, const model::ARNet<8>& model) noexcept;
    ~CUDAProcessor() noexcept override;

private:
    void process(const Image& src, Image& dst) override;

private:
    util::ThreadLocal<ImageBuffer> inImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp1ImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp2ImageBuffers{};
    util::ThreadLocal<ImageBuffer> featImageBuffers{};
    util::ThreadLocal<ImageBuffer> outImageBuffers{};
};

ac::core::cuda::CUDAProcessor<ac::core::model::ARNet<8>>::CUDAProcessor(const int device, const model::ARNet<8>& model) noexcept : CUDAProcessorSeqCNN(device, model) {}
ac::core::cuda::CUDAProcessor<ac::core::model::ARNet<8>>::~CUDAProcessor() noexcept = default;

void ac::core::cuda::CUDAProcessor<ac::core::model::ARNet<8>>::process(const Image& src, Image& dst)
{
    auto& err = errors.local();
    auto stream = cudaStreamPerThread;

    err = cudaSetDevice(idx); if (err != cudaSuccess) return;

    auto& inImageBuffer = inImageBuffers.local(allocator, stream);
    auto& tmp1ImageBuffer = tmp1ImageBuffers.local(allocator, stream);
    auto& tmp2ImageBuffer = tmp2ImageBuffers.local(allocator, stream);
    auto& featImageBuffer = featImageBuffers.local(allocator, stream);
    auto& outImageBuffer = outImageBuffers.local(allocator, stream);

    auto& in = inImageBuffer.get(src.width(), src.height(), src.channels(), src.type(), err); if (err != cudaSuccess) return;
    auto& tmp1 = tmp1ImageBuffer.get(src.width(), src.height(), 8, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& tmp2 = tmp2ImageBuffer.get(src.width(), src.height(), 8, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& feat = featImageBuffer.get(src.width(), src.height(), 8, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& out = outImageBuffer.get(dst.width(), dst.height(), dst.channels(), dst.type(), err); if (err != cudaSuccess) return;

    int l = 0;

    err = copyImageHostToDevice(in, src, stream); if (err != cudaSuccess) return;

    conv3x3_1to8_identity_cuda(in, feat, kernel(l), bias(l), stream); l++;

    conv3x3_8to8_prelu_cuda(feat, tmp1, kernel(l), bias(l), alpha(l), stream); l++;
    conv3x3_8to8_identity_residual_cuda(tmp1, tmp2, kernel(l), bias(l), feat, 0.2f, stream); l++;
    for (int i = 0; i < model.blocks() - 2; i++)
    {
        conv3x3_8to8_prelu_cuda(tmp2, tmp1, kernel(l), bias(l), alpha(l), stream); l++;
        conv3x3_8to8_identity_residual_cuda(tmp1, tmp2, kernel(l), bias(l), tmp2, 0.2f, stream); l++;
    }
    conv3x3_8to8_prelu_cuda(tmp2, tmp1, kernel(l), bias(l), alpha(l), stream); l++;
    conv3x3_8to8_identity_residual_conv1x1_8to8_prelu_add_cuda(tmp1, tmp2,
        kernel(l), bias(l), tmp2, 0.2f,
        kernel(l + 1), bias(l + 1), alpha(l + 1), feat, stream); l+=2;

    conv3x3_8to4_identity_pixelshuffle_4to1_add_cuda(tmp2, out, kernel(l), bias(l), in, stream);

    err = cudaPeekAtLastError(); if (err != cudaSuccess) return;

    err = copyImageDeviceToHost(dst, out, stream); if (err != cudaSuccess) return;

    err = cudaStreamSynchronize(stream); if (err != cudaSuccess) return;

    err = cudaPeekAtLastError();
}

template<>
AC_CORE_EXPORT std::shared_ptr<ac::core::Processor> ac::core::Processor::create<ac::core::Processor::CUDA, ac::core::model::ARNet<8>>(const int idx, const model::ARNet<8>& model)
{
    return std::make_shared<cuda::CUDAProcessor<model::ARNet<8>>>(idx, model);
}


template<>
class ac::core::cuda::CUDAProcessor<ac::core::model::ArtCNN<16>> : public CUDAProcessorSeqCNN<model::ArtCNN<16>>
{
public:
    CUDAProcessor(int device, const model::ArtCNN<16>& model) noexcept;
    ~CUDAProcessor() noexcept override;

private:
    void process(const Image& src, Image& dst) override;

private:
    util::ThreadLocal<ImageBuffer> inImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp1ImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp2ImageBuffers{};
    util::ThreadLocal<ImageBuffer> featImageBuffers{};
    util::ThreadLocal<ImageBuffer> outImageBuffers{};
};

ac::core::cuda::CUDAProcessor<ac::core::model::ArtCNN<16>>::CUDAProcessor(const int device, const model::ArtCNN<16>& model) noexcept : CUDAProcessorSeqCNN(device, model) {}
ac::core::cuda::CUDAProcessor<ac::core::model::ArtCNN<16>>::~CUDAProcessor() noexcept = default;

void ac::core::cuda::CUDAProcessor<ac::core::model::ArtCNN<16>>::process(const Image& src, Image& dst)
{
    auto& err = errors.local();
    auto stream = cudaStreamPerThread;

    err = cudaSetDevice(idx); if (err != cudaSuccess) return;

    auto& inImageBuffer = inImageBuffers.local(allocator, stream);
    auto& tmp1ImageBuffer = tmp1ImageBuffers.local(allocator, stream);
    auto& tmp2ImageBuffer = tmp2ImageBuffers.local(allocator, stream);
    auto& featImageBuffer = featImageBuffers.local(allocator, stream);
    auto& outImageBuffer = outImageBuffers.local(allocator, stream);

    auto& in = inImageBuffer.get(src.width(), src.height(), src.channels(), src.type(), err); if (err != cudaSuccess) return;
    auto& tmp1 = tmp1ImageBuffer.get(src.width(), src.height(), 16, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& tmp2 = tmp2ImageBuffer.get(src.width(), src.height(), 16, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& feat = featImageBuffer.get(src.width(), src.height(), 16, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& out = outImageBuffer.get(dst.width(), dst.height(), dst.channels(), dst.type(), err); if (err != cudaSuccess) return;

    auto tmpI = &tmp2;
    auto tmpO = &tmp1;
    int l = 0;

    err = copyImageHostToDevice(in, src, stream); if (err != cudaSuccess) return;

    conv3x3_1to16_identity_cuda(in, feat, kernel(l), bias(l), stream); l++;

    conv3x3_16to16_relu_cuda(feat, *tmpO, kernel(l), bias(l), stream); l++;
    std::swap(tmpI, tmpO);
    for (int i = 0; i < model.blocks() - 1; i++)
    {
        conv3x3_16to16_relu_cuda(*tmpI, *tmpO, kernel(l), bias(l), stream); l++;
        std::swap(tmpI, tmpO);
    }
    conv3x3_16to16_identity_add_cuda(*tmpI, *tmpO, kernel(l), bias(l), feat, stream); l++;
    std::swap(tmpI, tmpO);

    conv3x3_16to4_identity_pixelshuffle_4to1_cuda(*tmpI, out, kernel(l), bias(l), stream);

    err = cudaPeekAtLastError(); if (err != cudaSuccess) return;

    err = copyImageDeviceToHost(dst, out, stream); if (err != cudaSuccess) return;

    err = cudaStreamSynchronize(stream); if (err != cudaSuccess) return;

    err = cudaPeekAtLastError();
}

template<>
AC_CORE_EXPORT std::shared_ptr<ac::core::Processor> ac::core::Processor::create<ac::core::Processor::CUDA, ac::core::model::ArtCNN<16>>(const int idx, const model::ArtCNN<16>& model)
{
    return std::make_shared<cuda::CUDAProcessor<model::ArtCNN<16>>>(idx, model);
}


template<>
class ac::core::cuda::CUDAProcessor<ac::core::model::ArtCNN<32>> : public CUDAProcessorSeqCNN<model::ArtCNN<32>>
{
public:
    CUDAProcessor(int device, const model::ArtCNN<32>& model) noexcept;
    ~CUDAProcessor() noexcept override;

private:
    void process(const Image& src, Image& dst) override;

private:
    util::ThreadLocal<ImageBuffer> inImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp1ImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp2ImageBuffers{};
    util::ThreadLocal<ImageBuffer> featImageBuffers{};
    util::ThreadLocal<ImageBuffer> outImageBuffers{};
};

ac::core::cuda::CUDAProcessor<ac::core::model::ArtCNN<32>>::CUDAProcessor(const int device, const model::ArtCNN<32>& model) noexcept : CUDAProcessorSeqCNN(device, model) {}
ac::core::cuda::CUDAProcessor<ac::core::model::ArtCNN<32>>::~CUDAProcessor() noexcept = default;

void ac::core::cuda::CUDAProcessor<ac::core::model::ArtCNN<32>>::process(const Image& src, Image& dst)
{
    auto& err = errors.local();
    auto stream = cudaStreamPerThread;

    err = cudaSetDevice(idx); if (err != cudaSuccess) return;

    auto& inImageBuffer = inImageBuffers.local(allocator, stream);
    auto& tmp1ImageBuffer = tmp1ImageBuffers.local(allocator, stream);
    auto& tmp2ImageBuffer = tmp2ImageBuffers.local(allocator, stream);
    auto& featImageBuffer = featImageBuffers.local(allocator, stream);
    auto& outImageBuffer = outImageBuffers.local(allocator, stream);

    auto& in = inImageBuffer.get(src.width(), src.height(), src.channels(), src.type(), err); if (err != cudaSuccess) return;
    auto& tmp1 = tmp1ImageBuffer.get(src.width(), src.height(), 32, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& tmp2 = tmp2ImageBuffer.get(src.width(), src.height(), 32, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& feat = featImageBuffer.get(src.width(), src.height(), 32, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& out = outImageBuffer.get(dst.width(), dst.height(), dst.channels(), dst.type(), err); if (err != cudaSuccess) return;

    auto tmpI = &tmp2;
    auto tmpO = &tmp1;
    int l = 0;

    err = copyImageHostToDevice(in, src, stream); if (err != cudaSuccess) return;

    conv3x3_1to32_identity_cuda(in, feat, kernel(l), bias(l), stream); l++;

    conv3x3_32to32_relu_cuda(feat, *tmpO, kernel(l), bias(l), stream); l++;
    std::swap(tmpI, tmpO);
    for (int i = 0; i < model.blocks() - 1; i++)
    {
        conv3x3_32to32_relu_cuda(*tmpI, *tmpO, kernel(l), bias(l), stream); l++;
        std::swap(tmpI, tmpO);
    }
    conv3x3_32to32_identity_add_cuda(*tmpI, *tmpO, kernel(l), bias(l), feat, stream); l++;
    std::swap(tmpI, tmpO);

    conv3x3_32to4_identity_pixelshuffle_4to1_cuda(*tmpI, out, kernel(l), bias(l), stream);

    err = cudaPeekAtLastError(); if (err != cudaSuccess) return;

    err = copyImageDeviceToHost(dst, out, stream); if (err != cudaSuccess) return;

    err = cudaStreamSynchronize(stream); if (err != cudaSuccess) return;

    err = cudaPeekAtLastError();
}

template<>
AC_CORE_EXPORT std::shared_ptr<ac::core::Processor> ac::core::Processor::create<ac::core::Processor::CUDA, ac::core::model::ArtCNN<32>>(const int idx, const model::ArtCNN<32>& model)
{
    return std::make_shared<cuda::CUDAProcessor<model::ArtCNN<32>>>(idx, model);
}


template<>
class ac::core::cuda::CUDAProcessor<ac::core::model::FSRCNNX<8>> : public CUDAProcessorSeqCNN<model::FSRCNNX<8>>
{
public:
    CUDAProcessor(int device, const model::FSRCNNX<8>& model) noexcept;
    ~CUDAProcessor() noexcept override;

private:
    void process(const Image& src, Image& dst) override;

private:
    util::ThreadLocal<ImageBuffer> inImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp1ImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp2ImageBuffers{};
    util::ThreadLocal<ImageBuffer> featImageBuffers{};
    util::ThreadLocal<ImageBuffer> outImageBuffers{};
};

ac::core::cuda::CUDAProcessor<ac::core::model::FSRCNNX<8>>::CUDAProcessor(const int device, const model::FSRCNNX<8>& model) noexcept : CUDAProcessorSeqCNN(device, model) {}
ac::core::cuda::CUDAProcessor<ac::core::model::FSRCNNX<8>>::~CUDAProcessor() noexcept = default;

void ac::core::cuda::CUDAProcessor<ac::core::model::FSRCNNX<8>>::process(const Image& src, Image& dst)
{
    auto& err = errors.local();
    auto stream = cudaStreamPerThread;

    err = cudaSetDevice(idx); if (err != cudaSuccess) return;

    auto& inImageBuffer = inImageBuffers.local(allocator, stream);
    auto& tmp1ImageBuffer = tmp1ImageBuffers.local(allocator, stream);
    auto& tmp2ImageBuffer = tmp2ImageBuffers.local(allocator, stream);
    auto& featImageBuffer = featImageBuffers.local(allocator, stream);
    auto& outImageBuffer = outImageBuffers.local(allocator, stream);

    auto& in = inImageBuffer.get(src.width(), src.height(), src.channels(), src.type(), err); if (err != cudaSuccess) return;
    auto& tmp1 = tmp1ImageBuffer.get(src.width(), src.height(), 8, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& tmp2 = tmp2ImageBuffer.get(src.width(), src.height(), 8, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& feat = featImageBuffer.get(src.width(), src.height(), 8, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& out = outImageBuffer.get(dst.width(), dst.height(), dst.channels(), dst.type(), err); if (err != cudaSuccess) return;

    auto tmpI = &tmp2;
    auto tmpO = &tmp1;
    int l = 0;

    err = copyImageHostToDevice(in, src, stream); if (err != cudaSuccess) return;

    conv5x5_1to8_identity_cuda(in, feat, kernel(l), bias(l), stream); l++;

    conv3x3_8to8_prelu_cuda(feat, *tmpO, kernel(l), bias(l), alpha(l), stream); l++;
    std::swap(tmpI, tmpO);
    for (int i = 0; i < model.blocks() - 2; i++)
    {
        conv3x3_8to8_prelu_cuda(*tmpI, *tmpO, kernel(l), bias(l), alpha(l), stream); l++;
        std::swap(tmpI, tmpO);
    }
    conv3x3_8to8_prelu_conv1x1_8to8_add_prelu_cuda(*tmpI, *tmpO,
        kernel(l), bias(l), alpha(l),
        kernel(l + 1), bias(l + 1), alpha(l + 1), feat, stream); l += 2;
    std::swap(tmpI, tmpO);

    conv3x3_8to4_identity_pixelshuffle_4to1_cuda(*tmpI, out, kernel(l), bias(l), stream);

    err = cudaPeekAtLastError(); if (err != cudaSuccess) return;

    err = copyImageDeviceToHost(dst, out, stream); if (err != cudaSuccess) return;

    err = cudaStreamSynchronize(stream); if (err != cudaSuccess) return;

    err = cudaPeekAtLastError();
}

template<>
AC_CORE_EXPORT std::shared_ptr<ac::core::Processor> ac::core::Processor::create<ac::core::Processor::CUDA, ac::core::model::FSRCNNX<8>>(const int idx, const model::FSRCNNX<8>& model)
{
    return std::make_shared<cuda::CUDAProcessor<model::FSRCNNX<8>>>(idx, model);
}


template<>
class ac::core::cuda::CUDAProcessor<ac::core::model::FSRCNNX<16>> : public CUDAProcessorSeqCNN<model::FSRCNNX<16>>
{
public:
    CUDAProcessor(int device, const model::FSRCNNX<16>& model) noexcept;
    ~CUDAProcessor() noexcept override;

private:
    void process(const Image& src, Image& dst) override;

private:
    util::ThreadLocal<ImageBuffer> inImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp1ImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp2ImageBuffers{};
    util::ThreadLocal<ImageBuffer> featImageBuffers{};
    util::ThreadLocal<ImageBuffer> outImageBuffers{};
};

ac::core::cuda::CUDAProcessor<ac::core::model::FSRCNNX<16>>::CUDAProcessor(const int device, const model::FSRCNNX<16>& model) noexcept : CUDAProcessorSeqCNN(device, model) {}
ac::core::cuda::CUDAProcessor<ac::core::model::FSRCNNX<16>>::~CUDAProcessor() noexcept = default;

void ac::core::cuda::CUDAProcessor<ac::core::model::FSRCNNX<16>>::process(const Image& src, Image& dst)
{
    auto& err = errors.local();
    auto stream = cudaStreamPerThread;

    err = cudaSetDevice(idx); if (err != cudaSuccess) return;

    auto& inImageBuffer = inImageBuffers.local(allocator, stream);
    auto& tmp1ImageBuffer = tmp1ImageBuffers.local(allocator, stream);
    auto& tmp2ImageBuffer = tmp2ImageBuffers.local(allocator, stream);
    auto& featImageBuffer = featImageBuffers.local(allocator, stream);
    auto& outImageBuffer = outImageBuffers.local(allocator, stream);

    auto& in = inImageBuffer.get(src.width(), src.height(), src.channels(), src.type(), err); if (err != cudaSuccess) return;
    auto& tmp1 = tmp1ImageBuffer.get(src.width(), src.height(), 16, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& tmp2 = tmp2ImageBuffer.get(src.width(), src.height(), 16, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& feat = featImageBuffer.get(src.width(), src.height(), 16, DeviceImage::Float16, err); if (err != cudaSuccess) return;
    auto& out = outImageBuffer.get(dst.width(), dst.height(), dst.channels(), dst.type(), err); if (err != cudaSuccess) return;

    auto tmpI = &tmp2;
    auto tmpO = &tmp1;
    int l = 0;

    err = copyImageHostToDevice(in, src, stream); if (err != cudaSuccess) return;

    conv5x5_1to16_identity_cuda(in, feat, kernel(l), bias(l), stream); l++;

    conv3x3_16to16_prelu_cuda(feat, *tmpO, kernel(l), bias(l), alpha(l), stream); l++;
    std::swap(tmpI, tmpO);
    for (int i = 0; i < model.blocks() - 2; i++)
    {
        conv3x3_16to16_prelu_cuda(*tmpI, *tmpO, kernel(l), bias(l), alpha(l), stream); l++;
        std::swap(tmpI, tmpO);
    }
    conv3x3_16to16_prelu_conv1x1_16to16_add_prelu_cuda(*tmpI, *tmpO,
        kernel(l), bias(l), alpha(l), kernel(l + 1),
        bias(l + 1), alpha(l + 1), feat, stream); l += 2;
    std::swap(tmpI, tmpO);

    conv3x3_16to4_identity_pixelshuffle_4to1_cuda(*tmpI, out, kernel(l), bias(l), stream);

    err = cudaPeekAtLastError(); if (err != cudaSuccess) return;

    err = copyImageDeviceToHost(dst, out, stream); if (err != cudaSuccess) return;

    err = cudaStreamSynchronize(stream); if (err != cudaSuccess) return;

    err = cudaPeekAtLastError();
}

template<>
AC_CORE_EXPORT std::shared_ptr<ac::core::Processor> ac::core::Processor::create<ac::core::Processor::CUDA, ac::core::model::FSRCNNX<16>>(const int idx, const model::FSRCNNX<16>& model)
{
    return std::make_shared<cuda::CUDAProcessor<model::FSRCNNX<16>>>(idx, model);
}

template<>
AC_CORE_EXPORT const char* ac::core::Processor::info<ac::core::Processor::CUDA>()
{
    static auto infoBuffer = []() -> std::string {
        std::ostringstream buffer{ "CUDA:\n", std::ios_base::ate };
        for (int i = 0; i < ContextList.size(); i++)
            buffer << "  [" << i << "] " << ContextList[i].name << " (" << ContextList[i].vram << "MB, CC " << ContextList[i].computeCapability / 10.0 << ")" << '\n';
        return buffer.str();
    }();
    return infoBuffer.c_str();
}
