#ifndef AC_CORE_MODEL_ACNET_HPP
#define AC_CORE_MODEL_ACNET_HPP

#include <cstddef>

#include "ACExport.hpp" // Generated by CMake

namespace ac::core::model
{
    class ACNet;
}

class ac::core::model::ACNet
{
public:
    enum class Variant
    {
        GAN,
        HDN0,
        HDN1,
        HDN2,
        HDN3
    };

public:
    AC_EXPORT ACNet(Variant v) noexcept;

    template<typename T> const void* kernels() const noexcept;
    template<typename T> const void* biases() const noexcept;
    template<typename T> const T* kptr() const noexcept
    {
        return static_cast<const T*>(kernels<T>());
    }
    template<typename T> const T* bptr() const noexcept
    {
        return static_cast<const T*>(biases<T>());
    }

public:
    // length in numbers
    static constexpr int kernelLength() noexcept { return 8 * 9 + 8 * 8 * 9 * 8 + 8 * 4; }
    static constexpr int biasLength() noexcept { return 8 * 9; }
    static constexpr int kernelLength(const int idx) noexcept { return (idx == 0) ? 8 * 9 : ((idx > 0 && idx < 9) ? 8 * 8 * 9 : ((idx == 9) ? 8 * 4 : 0)); }
    static constexpr int biasLength(const int idx) noexcept { return (idx >= 0 && idx < 9) ? 8 : 0; }
    // size in bytes
    template <typename T>
    static constexpr std::size_t kernelSize() noexcept { return kernelLength() * sizeof(T); }
    template <typename T>
    static constexpr std::size_t biasSize() noexcept { return biasLength() * sizeof(T); }
    template <typename T>
    static constexpr std::size_t kernelSize(const int idx) noexcept { return kernelLength(idx) * sizeof(T); }
    template <typename T>
    static constexpr std::size_t biasSize(const int idx) noexcept { return biasLength(idx) * sizeof(T); }

    static constexpr const char* name() noexcept { return "ACNet"; }

public:
    static constexpr int kernelOffset[]{
        0,
        0 * 8 * 8 * 9 + 8 * 9,
        1 * 8 * 8 * 9 + 8 * 9,
        2 * 8 * 8 * 9 + 8 * 9,
        3 * 8 * 8 * 9 + 8 * 9,
        4 * 8 * 8 * 9 + 8 * 9,
        5 * 8 * 8 * 9 + 8 * 9,
        6 * 8 * 8 * 9 + 8 * 9,
        7 * 8 * 8 * 9 + 8 * 9,
        8 * 8 * 8 * 9 + 8 * 9
    };
    static constexpr int baisOffset[]{
        0,
        1 * 8,
        2 * 8,
        3 * 8,
        4 * 8,
        5 * 8,
        6 * 8,
        7 * 8,
        8 * 8
    };

private:
    const Variant variant;
};

#endif
