#ifndef AC_CORE_MODEL_ACNET_HPP
#define AC_CORE_MODEL_ACNET_HPP

#include <algorithm>

#include "AC/Core/Model/Base.hpp"

#include "ACCoreExport.hpp" // Generated by CMake

namespace ac::core::model
{
    class ACNetClassic;

    template<int F>
    class ACNet;
}

class ac::core::model::ACNetClassic : public BaseModel<ACNetClassic>
{
public:
    enum class Variant
    {
        GAN,
        HDN0,
        HDN1,
        HDN2,
        HDN3
    };

public:
    AC_CORE_EXPORT ACNetClassic(Variant v) noexcept;

public:
    int kernelLength() const noexcept { return 8 * 9 + 8 * 8 * 9 * 8 + 8 * 4; }
    int kernelLength(const int layer) const noexcept { return (layer == 0) ? 8 * 9 : ((layer > 0 && layer < 9) ? 8 * 8 * 9 : ((layer == 9) ? 8 * 4 : 0)); }
    int biasLength() const noexcept { return 8 * 9; }
    int biasLength(const int layer) const noexcept { return (layer >= 0 && layer < 9) ? 8 : 0; }

    int kernels() const noexcept { return 10; }
    int biases() const noexcept { return 9; }

    int kernelIndex(const int layer) const  noexcept { return std::clamp(layer, 0, kernels() - 1); }
    int biasIndex(const int layer) const noexcept { return std::clamp(layer, 0, biases() - 1); }

    int kernelLayer(const int idx) const noexcept { return std::clamp(idx, 0, kernels() - 1); }
    int biasLayer(const int idx) const noexcept { return std::clamp(idx, 0, biases() - 1); }

    int kernelOffset(const int layer) const noexcept
    {
        if (layer <= 0) return 0;
        if (layer <= 1) return 8 * 9;
        if (layer < kernels()) return 8 * 9 + (8 * 8 * 9) * (layer - 1);
        return kernelLength();
    }
    int biasOffset(const int layer) const noexcept
    {
        if (layer <= 0) return 0;
        if (layer < biases()) return 8 * layer;
        return biasLength();
    }
};

template<int F>
class ac::core::model::ACNet : public BaseModel<ACNet<F>>
{
public:
    enum class Variant
    {
        B8_NORMAL, B8_HDN
    };

public:
    AC_CORE_EXPORT ACNet(Variant v) noexcept;

public:
    int kernelLength() const noexcept { return F * 9 + F * F * 9 * blockNum + F * 4 * 9; }
    int kernelLength(const int layer) const noexcept { return (layer == 0) ? F * 9 : ((layer > 0 && layer < (blockNum + 1)) ? F * F * 9 : ((layer == (blockNum + 1)) ? F * 4 * 9 : 0)); }
    int biasLength() const noexcept { return F + F * blockNum + 4; }
    int biasLength(const int layer) const noexcept { return (layer >= 0 && layer < (blockNum + 1)) ? F : (layer == (blockNum + 1) ? 4 : 0); }
    int alphaLength() const noexcept { return F * (blockNum + 1); }
    int alphaLength(const int layer) const noexcept { return (layer >= 0 && layer < (blockNum + 1)) ? F : 0; }

    int kernels() const noexcept { return blockNum + 1 + 1; }
    int biases() const noexcept { return blockNum + 1 + 1; }
    int alphas() const noexcept { return blockNum + 1; }

    int kernelIndex(const int layer) const noexcept { return std::clamp(layer, 0, kernels() - 1); }
    int biasIndex(const int layer) const noexcept { return std::clamp(layer, 0, biases() - 1); }
    int alphaIndex(const int layer) const noexcept { return std::clamp(layer, 0, alphas() - 1); }

    int kernelLayer(const int idx) const noexcept { return std::clamp(idx, 0, kernels() - 1); }
    int biasLayer(const int idx) const noexcept { return std::clamp(idx, 0, biases() - 1); }
    int alphaLayer(const int idx) const noexcept { return std::clamp(idx, 0, alphas() - 1); }

    int kernelOffset(const int layer) const noexcept
    {
        if (layer <= 0) return 0;
        if (layer <= 1) return F * 9;
        if (layer < kernels()) return F * 9 + (F * F * 9) * (layer - 1);
        return kernelLength();
    }
    int biasOffset(const int layer) const noexcept
    {
        if (layer <= 0) return 0;
        if (layer < biases()) return F * layer;
        return biasLength();
    }
    int alphaOffset(const int layer) const noexcept
    {
        if (layer <= 0) return 0;
        if (layer < alphas()) return F * layer;
        return alphaLength();
    }
};

#endif
