#ifndef AC_CORE_MODEL_ARNET_HPP
#define AC_CORE_MODEL_ARNET_HPP

#include <cstddef>

#include "AC/Core/Model/Base.hpp"

#include "ACExport.hpp" // Generated by CMake

namespace ac::core::model
{
    class ARNet;
}

class ac::core::model::ARNet
{
    AC_CORE_SEQ_CNN_MODEL(ARNet)

public:
    enum class Variant
    {
        SMALL_NORMAL, SMALL_LE
    };

public:
    AC_EXPORT ARNet(Variant v) noexcept;

public:
    int blocks() const noexcept { return blockNum; }

    // length in numbers
    int kernelLength() const noexcept { return 8 * 9 + 8 * 8 * 9 * blockNum * 2 + 8 * 4 * 9; }
    int biasLength() const noexcept { return 8 + 8 * blockNum * 2 + 4; }
    int kernelLength(const int idx) const noexcept { return (idx == 0) ? 8 * 9 : ((idx > 0 && idx < (blockNum * 2 + 1)) ? 8 * 8 * 9 : ((idx == (blockNum * 2 + 1)) ? 8 * 4 * 9 : 0)); }
    int biasLength(const int idx) const noexcept { return (idx >= 0 && idx < (blockNum * 2 + 1)) ? 8 : (idx == (blockNum * 2 + 1) ? 4 : 0); }

    // size in bytes
    std::size_t kernelSize() const noexcept { return kernelLength() * sizeof(float); }
    std::size_t biasSize() const noexcept { return biasLength() * sizeof(float); }
    std::size_t kernelSize(const int idx) const noexcept { return kernelLength(idx) * sizeof(float); }
    std::size_t biasSize(const int idx) const noexcept { return biasLength(idx) * sizeof(float); }

    int kernelOffset(const int idx) const noexcept
    {
        if (idx <= 0) return 0;
        if (idx == 1) return 8 * 9;
        if (idx <= blockNum * 2 + 1) return 8 * 9 + (8 * 8 * 9) * (idx - 1);
        return kernelLength();
    }
    int baisOffset(const int idx) const noexcept
    {
        if (idx <= 0) return 0;
        if (idx == 1) return 8;
        if (idx <= blockNum * 2 + 1) return 8 + 8 * (idx - 1);
        return biasLength();
    }
private:
    int blockNum;
};

#endif
