#ifndef AC_CORE_MODEL_ARTCNN_HPP
#define AC_CORE_MODEL_ARTCNN_HPP

#include <algorithm>

#include "AC/Core/Model/Base.hpp"

#include "ACCoreExport.hpp" // Generated by CMake

namespace ac::core::model
{
    template<int F>
    class ArtCNN;
}

template<int F>
class ac::core::model::ArtCNN : public BaseModel<ArtCNN<F>>
{
public:
    enum class Variant
    {
        NORMAL, DN, DS
    };

public:
    AC_CORE_EXPORT ArtCNN(Variant v) noexcept;

public:
    int kernelLength() const noexcept { return F * 9 + F * F * 9 * (this->blockNum + 1) + F * 4 * 9; }
    int kernelLength(const int layer) const noexcept { return (layer == 0) ? F * 9 : ((layer > 0 && layer < (this->blockNum + 1 + 1)) ? F * F * 9 : ((layer == (this->blockNum + 1 + 1)) ? F * 4 * 9 : 0)); }
    int biasLength() const noexcept { return F + F * (this->blockNum + 1) + 4; }
    int biasLength(const int layer) const noexcept { return (layer >= 0 && layer < (this->blockNum + 1 + 1)) ? F : (layer == (this->blockNum + 1 + 1) ? 4 : 0); }

    int kernels() const noexcept { return this->blockNum + 1 + 2; }
    int biases() const noexcept { return this->blockNum + 1 + 2; }

    int kernelIndex(const int layer) const noexcept { return std::clamp(layer, 0, kernels() - 1); }
    int biasIndex(const int layer) const noexcept { return std::clamp(layer, 0, biases() - 1); }

    int kernelLayer(const int idx) const noexcept { return std::clamp(idx, 0, kernels() - 1); }
    int biasLayer(const int idx) const noexcept { return std::clamp(idx, 0, biases() - 1); }

    int kernelOffset(const int layer) const noexcept
    {
        if (layer <= 0) return 0;
        if (layer <= 1) return F * 9;
        if (layer < kernels()) return F * 9 + (F * F * 9) * (layer - 1);
        return kernelLength();
    }
    int biasOffset(const int layer) const noexcept
    {
        if (layer <= 0) return 0;
        if (layer < biases()) return F * layer;
        return biasLength();
    }
};

#endif
