#ifndef AC_CORE_MODEL_BASE_MODE_HPP
#define AC_CORE_MODEL_BASE_MODE_HPP

#include <cstddef>

#include "ACCoreExport.hpp" // Generated by CMake

namespace ac::core::model
{
    template<typename Model>
    class BaseModel;
}

template<typename Model>
class ac::core::model::BaseModel
{
public:
    AC_CORE_EXPORT BaseModel() noexcept;

public:
    // length in numbers
    int kernelLength() const noexcept { return 0; }
    int kernelLength(const int /*layer*/) const noexcept { return 0; }
    int biasLength() const noexcept { return 0; }
    int biasLength(const int /*layer*/) const noexcept { return 0; }
    int alphaLength() const noexcept { return 0; }
    int alphaLength(const int /*layer*/) const noexcept { return 0; }
    // size in bytes
    std::size_t kernelSize() const noexcept { return static_cast<const Model*>(this)->kernelLength() * sizeof(float); }
    std::size_t kernelSize(const int layer) const noexcept { return static_cast<const Model*>(this)->kernelLength(layer) * sizeof(float); }
    std::size_t biasSize() const noexcept { return static_cast<const Model*>(this)->biasLength() * sizeof(float); }
    std::size_t biasSize(const int layer) const noexcept { return static_cast<const Model*>(this)->biasLength(layer) * sizeof(float); }
    std::size_t alphaSize() const noexcept { return static_cast<const Model*>(this)->alphaLength() * sizeof(float); }
    std::size_t alphaSize(const int layer) const noexcept { return static_cast<const Model*>(this)->alphaLength(layer) * sizeof(float); }

    int blocks() const noexcept { return blockNum; }
    int kernels() const noexcept { return 0; }
    int biases() const noexcept { return 0; }
    int alphas() const noexcept { return 0; }

    int kernelIndex(const int /*layer*/) const noexcept { return 0; }
    int biasIndex(const int /*layer*/) const noexcept { return 0; }
    int alphaIndex(const int /*layer*/) const noexcept { return 0; }

    int kernelLayer(const int /*idx*/) const noexcept { return 0; }
    int biasLayer(const int /*idx*/) const noexcept { return 0; }
    int alphaLayer(const int /*idx*/) const noexcept { return 0; }

    int kernelOffset(const int /*layer*/) const noexcept { return 0; }
    int biasOffset(const int /*layer*/) const noexcept { return 0; }
    int alphaOffset(const int /*layer*/) const noexcept { return 0; }

    const float* kernel(const int layer = 0) const noexcept { return kptr + static_cast<const Model*>(this)->kernelOffset(layer); }
    const float* bias(const int layer = 0) const noexcept { return bptr + static_cast<const Model*>(this)->biasOffset(layer); }
    const float* alpha(const int layer = 0) const noexcept { return aptr + static_cast<const Model*>(this)->alphaOffset(layer); }

protected:
    int blockNum;

    const float* kptr;
    const float* bptr;
    const float* aptr;
};

#endif
