#ifndef AC_CORE_MODEL_FSRCNNX_HPP
#define AC_CORE_MODEL_FSRCNNX_HPP

#include <algorithm>
#include <cstddef>

#include "ACCoreExport.hpp" // Generated by CMake

namespace ac::core::model
{
    template<int F>
    class FSRCNNX;
}

template<int F>
class ac::core::model::FSRCNNX
{
public:
    enum class Variant
    {
        NORMAL, DISTORT_PLUS
    };

public:
    AC_CORE_EXPORT FSRCNNX(Variant v) noexcept;

public:
    // length in numbers
    int kernelLength() const noexcept { return F * 25 + F * F * 9 * blockNum + F * F * 1 + F * 4 * 9; }
    int biasLength() const noexcept { return F + F * (blockNum + 1) + 4; }
    int alphaLength() const noexcept { return F * (blockNum + 1); }
    int kernelLength(const int layer) const noexcept { return (layer == 0) ? F * 25 : ((layer > 0 && layer < (blockNum + 1)) ? F * F * 9 : ((layer == (blockNum + 1)) ? F * F * 1 : ((layer == (blockNum + 1 + 1)) ? F * 4 * 9: 0))); }
    int biasLength(const int layer) const noexcept { return (layer >= 0 && layer < (blockNum + 1 + 1)) ? F : (layer == (blockNum + 1 + 1) ? 4 : 0); }
    int alphaLength(const int layer) const noexcept { return (layer >= 1 && layer < (blockNum + 1 + 1)) ? F : 0; }
    // size in bytes
    std::size_t kernelSize() const noexcept { return kernelLength() * sizeof(float); }
    std::size_t biasSize() const noexcept { return biasLength() * sizeof(float); }
    std::size_t alphaSize() const noexcept { return alphaLength() * sizeof(float); }
    std::size_t kernelSize(const int layer) const noexcept { return kernelLength(layer) * sizeof(float); }
    std::size_t biasSize(const int layer) const noexcept { return biasLength(layer) * sizeof(float); }
    std::size_t alphaSize(const int layer) const noexcept { return alphaLength(layer) * sizeof(float); }

    int blocks() const noexcept { return blockNum; }
    int kernels() const noexcept { return blockNum + 1 + 2; }
    int biases() const noexcept { return blockNum + 1 + 2; }
    int alphas() const noexcept { return blockNum + 1; }

    int kernelIndex(const int layer) const noexcept { return std::clamp(layer, 0, kernels() - 1); }
    int biasIndex(const int layer) const noexcept { return std::clamp(layer, 0, biases() - 1); }
    int alphaIndex(const int layer) const noexcept { return std::clamp(layer, 1, alphas()) - 1; }

    int kernelLayer(const int idx) const noexcept { return std::clamp(idx, 0, kernels() - 1); }
    int biasLayer(const int idx) const noexcept { return std::clamp(idx, 0, biases() - 1); }
    int alphaLayer(const int idx) const noexcept { return std::clamp(idx, 0, alphas() - 1) + 1; }

    int kernelOffset(const int layer) const noexcept
    {
        if (layer <= 0) return 0;
        if (layer <= 1) return F * 25;
        if (layer <= (blockNum + 1)) return F * 25 + F * F * 9 * (layer - 1);
        if (layer < kernels()) return F * 25 + F * F * 9 * blockNum + F * F * 1;
        return kernelLength();
    }
    int biasOffset(const int layer) const noexcept
    {
        if (layer <= 0) return 0;
        if (layer < biases()) return F * layer;
        return biasLength();
    }
    int alphaOffset(const int layer) const noexcept
    {
        auto idx = alphaIndex(layer);
        if (idx <= 0) return 0;
        if (idx < alphas()) return F * idx;
        return alphaLength();
    }

    const float* kernel(const int layer = 0) const noexcept { return kptr + kernelOffset(layer); }
    const float* bias(const int layer = 0) const noexcept { return bptr + biasOffset(layer); }
    const float* alpha(const int layer = 0) const noexcept { return aptr + alphaOffset(layer); }

private:
    int blockNum;

    const float* kptr;
    const float* bptr;
    const float* aptr;
};

#endif
