enable_language(HIP)

set(CMAKE_HIP_STANDARD 17)
set(CMAKE_HIP_STANDARD_REQUIRED ON)
set(CMAKE_HIP_EXTENSIONS OFF)
# 7700XT
set(CMAKE_HIP_ARCHITECTURES gfx1101 CACHE STRING "HIP architectures" FORCE)
