#include <cassert>
#include <cctype>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

#if __has_include(<CL/opencl.hpp>)
#   include <CL/opencl.hpp>
#elif __has_include(<CL/cl2.hpp>)
#   include <CL/cl2.hpp>
#else
#   include <CL/cl.hpp>
#endif

#include "AC/Core/Model.hpp"
#include "AC/Core/Processor.hpp"
#include "AC/Core/Util.hpp"
#include "AC/Util/ThreadLocal.hpp"

#include "AC/Core/Processor/OpenCL/CommonKernel.hpp" // Generated by CMake
#include "AC/Core/Processor/OpenCL/ACNetKernel.hpp"  // Generated by CMake
#include "AC/Core/Processor/OpenCL/ARNetKernel.hpp"  // Generated by CMake

#include "ACCoreExport.hpp" // Generated by CMake

namespace ac::core::opencl
{
    class Arch
    {
    public:
        enum Value
        {
            AMD_RDNA,
            AMD_GCN,
            INTEL,
            NVIDIA,
            ADRENO,
            MESA,
            OTHER,
        };

    public:
        constexpr explicit Arch(Value v = OTHER) noexcept : value(v) {}
        constexpr Arch& operator=(Value v) noexcept { value = v; return *this; }
        constexpr operator Value() const noexcept { return value; }
        constexpr const char* name() const noexcept
        {
            switch (value)
            {
            case AMD_RDNA: return "AMD_RDNA";
            case AMD_GCN: return "AMD_GCN";
            case INTEL: return "INTEL";
            case NVIDIA: return "NVIDIA";
            case ADRENO: return "ADRENO";
            case MESA: return "MESA";
            default: return "OTHER";
            }
        }

    private:
        Value value;
    };

    struct KernelBuildData
    {
        const char* kernelString;
        std::string compileOptions;
        bool passWeightsByConstant;
    };

    struct Context
    {
        std::string name{};
        std::string info{};
        cl::Device device{};
        cl::Context ctx{};
        cl::Program program{};
        Arch arch{};
        cl_ulong constantMemorySize{};

        Context() noexcept = default;
        Context(const cl::Platform& platform, const cl::Device& device) noexcept : device(device)
        {
            std::string platformName{ "Unknown" };
            platform.getInfo(CL_PLATFORM_NAME, &platformName);

            bool amdapp = platformName == "AMD Accelerated Parallel Processing";

            std::string deviceName{ "Unknown" };
            device.getInfo(CL_DEVICE_NAME, &deviceName);

            if (amdapp)
            {
                std::string boardNameAMD{ "Unknown" };
                device.getInfo(0x4038 /*CL_DEVICE_BOARD_NAME_AMD*/, &boardNameAMD);

                name = boardNameAMD;
                info.append(deviceName).append(", ");
            }
            else name = deviceName;

            std::string driverVersion{ "Unknown" };
            device.getInfo(CL_DRIVER_VERSION, &driverVersion);

            info.append(platformName).append(", ").append(driverVersion);

            if (platformName == "rusticl") arch = Arch::MESA;
            else
            {
                cl_uint vendorId{};
                if (device.getInfo(CL_DEVICE_VENDOR_ID, &vendorId) == CL_SUCCESS)
                {
                    switch (vendorId)
                    {
                    case 0x1002: // AMD
                        if (auto pos = name.find("gfx"); pos != std::string::npos && std::isdigit(static_cast<unsigned char>(name[pos + 6]))) // gfx1000 or newer
                            arch = Arch::AMD_RDNA;
                        else
                            arch = Arch::AMD_GCN;
                        break;
                    case 0x8086: // Intel
                        arch = Arch::INTEL;
                        break;
                    case 0x10DE: // Nvidia
                        arch = Arch::NVIDIA;
                        break;
                    case 0x5143: // Qualcomm
                        arch = Arch::ADRENO;
                        break;
                    }
                }
            }

            device.getInfo(CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE, &constantMemorySize);
        }
    };

    // we need the device with image support
    static inline bool checkDevice(const cl::Device& device)
    {
        cl_int err = CL_SUCCESS;
        auto imageSupport = device.getInfo<CL_DEVICE_IMAGE_SUPPORT>(&err);
        if (err != CL_SUCCESS || imageSupport != CL_TRUE) return false;
        return true;
    }

    // we cannot make ContextList as static like cuda.
    // it will crash while unload the DLL(if build this into a DLL), god knows why.
    static inline std::vector<Context> getContextList() noexcept
    {
        std::vector<Context> contexts{};
        std::vector<cl::Platform> platforms{};
        cl::Platform::get(&platforms);
        for (auto&& platform : platforms)
        {
            std::vector<cl::Device> devices{};
            platform.getDevices(CL_DEVICE_TYPE_ALL, &devices);

            for (auto&& device : devices)
                if (checkDevice(device)) contexts.emplace_back(platform, device);
        }
        return contexts;
    }

    // we can call `init` multiple times
    static inline cl_int init(Context& context, const KernelBuildData& buildData) noexcept
    {
        if (!context.device()) return CL_DEVICE_NOT_AVAILABLE;
        if (context.ctx() && context.program()) return CL_SUCCESS;

        cl_int err = CL_SUCCESS;
        context.ctx = cl::Context{ context.device, nullptr, nullptr, nullptr, &err }; if (err != CL_SUCCESS) return err;

        std::string options{};
        if (buildData.passWeightsByConstant) options.append("-DPASS_WEIGHTS_BY_CONSTANT ");
#   ifdef AC_CORE_ENABLE_FAST_MATH
        options.append("-cl-fast-relaxed-math ");
#   endif
        options.append("-DARCH_").append(context.arch.name()).append(" ").append(buildData.compileOptions);


        cl::Program kernelProgram{ context.ctx, buildData.kernelString, false, &err }; if (err != CL_SUCCESS) return err;
        cl::Program commonProgram{ context.ctx, kernel::CommonKernelString, false, &err }; if (err != CL_SUCCESS) return err;

        err = kernelProgram.compile(options.c_str(), { context.device }, { commonProgram }, { "CommonKernel.cl" }); if (err != CL_SUCCESS) return err;
        context.program = cl::linkProgram({ kernelProgram }, nullptr, nullptr, nullptr, &err);
        return err;
    }
    static inline cl_channel_type channelType(const Image::ElementType elementType) noexcept
    {
        switch (elementType)
        {
        case Image::UInt8: return CL_UNORM_INT8;
        case Image::UInt16: return CL_UNORM_INT16;
        case Image::Float32: return CL_FLOAT;
        default: return assert(elementType == Image::UInt8 || elementType == Image::UInt16 || elementType == Image::Float32), CL_UNORM_INT8;
        }
    }

    class ImageBuffer : private cl::Image
    {
    public:
        ImageBuffer() noexcept = default;
        ImageBuffer(const ImageBuffer&) = delete;
        ImageBuffer(ImageBuffer&&) noexcept = delete;
        ImageBuffer& operator=(const ImageBuffer&) = delete;

        const cl::Image& get(
            const cl::Context& ctx,
            const cl_mem_flags flags,
            const cl_channel_order channelOrder,
            const cl_channel_type channelType,
            const cl::size_type channels,
            const cl::size_type width,
            const cl::size_type height,
            cl_int* const err)
        {
            if (!object_ || w != width || h != height || type != channelType)
            {
                auto arraySize = (channels + 3) / 4;

                if (arraySize < 2)
                    *this = cl::Image2D{ ctx, flags, {channelOrder, channelType}, width, height, 0, nullptr, err };
                else
                    *this = cl::Image2DArray{ ctx, flags, {channelOrder, channelType}, arraySize, width, height, 0, 0, nullptr, err };

                if (!err || *err == CL_SUCCESS)
                {
                    w = width;
                    h = height;
                    type = channelType;
                }
                else *this = ImageBuffer{};
            }
            return *this;
        }

    private:
        ImageBuffer& operator=(ImageBuffer&&) noexcept = default;
        using cl::Image::operator=;

    private:
        cl::size_type h{}, w{};
        cl_channel_type type{};
    };

    class OpenCLProcessorBase : public Processor
    {
    public:
        OpenCLProcessorBase(const int device) noexcept
        {
            auto& err = errors.local();
            auto contextList = getContextList();
            if (contextList.empty()) err = CL_DEVICE_NOT_FOUND;
            else
            {
                idx = (device >= 0 && static_cast<decltype(contextList.size())>(device) < contextList.size()) ? device : 0;
                context = contextList[idx];
            }
        }
        ~OpenCLProcessorBase() noexcept override = default;

        bool ok() noexcept override
        {
            return errors.local() == CL_SUCCESS;
        }
        const char* error() noexcept override
        {
            switch (errors.local())
            {// run-time and JIT compiler errors
            case 0: return "CL_SUCCESS";
            case -1: return "CL_DEVICE_NOT_FOUND";
            case -2: return "CL_DEVICE_NOT_AVAILABLE";
            case -3: return "CL_COMPILER_NOT_AVAILABLE";
            case -4: return "CL_MEM_OBJECT_ALLOCATION_FAILURE";
            case -5: return "CL_OUT_OF_RESOURCES";
            case -6: return "CL_OUT_OF_HOST_MEMORY";
            case -7: return "CL_PROFILING_INFO_NOT_AVAILABLE";
            case -8: return "CL_MEM_COPY_OVERLAP";
            case -9: return "CL_IMAGE_FORMAT_MISMATCH";
            case -10: return "CL_IMAGE_FORMAT_NOT_SUPPORTED";
            case -11: return "CL_BUILD_PROGRAM_FAILURE";
            case -12: return "CL_MAP_FAILURE";
            case -13: return "CL_MISALIGNED_SUB_BUFFER_OFFSET";
            case -14: return "CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST";
            case -15: return "CL_COMPILE_PROGRAM_FAILURE";
            case -16: return "CL_LINKER_NOT_AVAILABLE";
            case -17: return "CL_LINK_PROGRAM_FAILURE";
            case -18: return "CL_DEVICE_PARTITION_FAILED";
            case -19: return "CL_KERNEL_ARG_INFO_NOT_AVAILABLE";
                // compile-time errors
            case -30: return "CL_INVALID_VALUE";
            case -31: return "CL_INVALID_DEVICE_TYPE";
            case -32: return "CL_INVALID_PLATFORM";
            case -33: return "CL_INVALID_DEVICE";
            case -34: return "CL_INVALID_CONTEXT";
            case -35: return "CL_INVALID_QUEUE_PROPERTIES";
            case -36: return "CL_INVALID_COMMAND_QUEUE";
            case -37: return "CL_INVALID_HOST_PTR";
            case -38: return "CL_INVALID_MEM_OBJECT";
            case -39: return "CL_INVALID_IMAGE_FORMAT_DESCRIPTOR";
            case -40: return "CL_INVALID_IMAGE_SIZE";
            case -41: return "CL_INVALID_SAMPLER";
            case -42: return "CL_INVALID_BINARY";
            case -43: return "CL_INVALID_BUILD_OPTIONS";
            case -44: return "CL_INVALID_PROGRAM";
            case -45: return "CL_INVALID_PROGRAM_EXECUTABLE";
            case -46: return "CL_INVALID_KERNEL_NAME";
            case -47: return "CL_INVALID_KERNEL_DEFINITION";
            case -48: return "CL_INVALID_KERNEL";
            case -49: return "CL_INVALID_ARG_INDEX";
            case -50: return "CL_INVALID_ARG_VALUE";
            case -51: return "CL_INVALID_ARG_SIZE";
            case -52: return "CL_INVALID_KERNEL_ARGS";
            case -53: return "CL_INVALID_WORK_DIMENSION";
            case -54: return "CL_INVALID_WORK_GROUP_SIZE";
            case -55: return "CL_INVALID_WORK_ITEM_SIZE";
            case -56: return "CL_INVALID_GLOBAL_OFFSET";
            case -57: return "CL_INVALID_EVENT_WAIT_LIST";
            case -58: return "CL_INVALID_EVENT";
            case -59: return "CL_INVALID_OPERATION";
            case -60: return "CL_INVALID_GL_OBJECT";
            case -61: return "CL_INVALID_BUFFER_SIZE";
            case -62: return "CL_INVALID_MIP_LEVEL";
            case -63: return "CL_INVALID_GLOBAL_WORK_SIZE";
            case -64: return "CL_INVALID_PROPERTY";
            case -65: return "CL_INVALID_IMAGE_DESCRIPTOR";
            case -66: return "CL_INVALID_COMPILER_OPTIONS";
            case -67: return "CL_INVALID_LINKER_OPTIONS";
            case -68: return "CL_INVALID_DEVICE_PARTITION_COUNT";
            case -69: return "CL_INVALID_PIPE_SIZE";
            case -70: return "CL_INVALID_DEVICE_QUEUE";
            case -71: return "CL_INVALID_SPEC_ID";
            case -72: return "CL_MAX_SIZE_RESTRICTION_EXCEEDED";
                // extension errors
            case -1001: return "CL_PLATFORM_NOT_FOUND_KHR";
            default: return "CL_UNKNOWN_ERROR";
            }
        }
        const char* name() const noexcept override
        {
            return context.name.c_str();
        }
        int type() const noexcept override
        {
            return Processor::OpenCL;
        }
        const char* typeName() const noexcept override
        {
            return "OpenCL";
        }
    protected:
        struct WorkGroupSize
        {
            static constexpr int x = 16;
            static constexpr int y = 8;
        };
    protected:
        Context context{};
        util::ThreadLocal<cl_int> errors{};
        util::ThreadLocal<cl::CommandQueue> queues{};
    };

    template<typename Model>
    class OpenCLProcessorSeqCNN : public OpenCLProcessorBase
    {
    public:
        OpenCLProcessorSeqCNN(const int device, const Model& model, const char* kernelString) noexcept : OpenCLProcessorBase(device), model(model), splitWeights(false)
        {
            auto& err = errors.local();
            if (err != CL_SUCCESS) return; // check if initialization was successful

            // Determine whether to split weights into separate buffers:
            // - AMD RDNA: Never split weights (optimized for contiguous memory access)
            // - Adreno: Always split weights (better performance with smaller buffers)
            // - Other architectures: Split only if total weights exceed device's constant memory limit
            if (context.arch != Arch::AMD_RDNA && (
                model.kernelSize() > context.constantMemorySize ||
                model.biasSize() > context.constantMemorySize ||
                context.arch == Arch::ADRENO)) splitWeights = true;

            // Configure kernel build options:
            // - If weights are split: Don't use offset calculations (each layer has its own buffer)
            // - If weights are NOT split: Use offset calculations to index into single buffer
            // - Use constant memory for weights when:
            //   a) Weights are split (each smaller buffer fits in constant memory), OR
            //   b) Total weights fit in constant memory (fastest access for unsplit weights)
            //   Note: AMD RDNA with oversized weights cannot use constant memory (fallback to global)
            KernelBuildData buildData {
                kernelString,
                splitWeights ? "" : "-DUSE_WEIGHTS_OFFSET",
                splitWeights || (model.kernelSize() <= context.constantMemorySize && model.biasSize() <= context.constantMemorySize)
            };

            err = init(context, buildData); if (err != CL_SUCCESS) return;

            if (splitWeights)
            {
                for (int i = 0; i < model.kernels(); i++)
                {
                    kernels.emplace_back(
                        context.ctx,
                        CL_MEM_READ_ONLY | CL_MEM_HOST_NO_ACCESS | CL_MEM_COPY_HOST_PTR,
                        model.kernelSize(i),
                        const_cast<float*>(model.kernel(i)),
                        &err
                    );
                    if (err != CL_SUCCESS) return;
                }

                for (int i = 0; i < model.biases(); i++)
                {
                    biases.emplace_back(
                        context.ctx,
                        CL_MEM_READ_ONLY | CL_MEM_HOST_NO_ACCESS | CL_MEM_COPY_HOST_PTR,
                        model.biasSize(i),
                        const_cast<float*>(model.bias(i)),
                        &err
                    );
                    if (err != CL_SUCCESS) return;
                }
            }
            else
            {
                kernels.emplace_back(
                    context.ctx,
                    CL_MEM_READ_ONLY | CL_MEM_HOST_NO_ACCESS | CL_MEM_COPY_HOST_PTR,
                    model.kernelSize(),
                    const_cast<float*>(model.kernel()),
                    &err
                ); if (err != CL_SUCCESS) return;

                biases.emplace_back(
                    context.ctx,
                    CL_MEM_READ_ONLY | CL_MEM_HOST_NO_ACCESS | CL_MEM_COPY_HOST_PTR,
                    model.biasSize(),
                    const_cast<float*>(model.bias()),
                    &err
                ); if (err != CL_SUCCESS) return;
            }
        }
        ~OpenCLProcessorSeqCNN() noexcept override = default;

    protected:
        const cl::Buffer& kernel(const int l) const noexcept
        {
            return splitWeights ? kernels[l] : kernels.front();
        }
        const cl::Buffer& bias(const int l) const noexcept
        {
            return splitWeights ? biases[l] : biases.front();
        }
        int kernelOffset(const int l) const noexcept
        {
            return splitWeights ? 0 : model.kernelOffset(l);
        }
        int biasOffset(const int l) const noexcept
        {
            return splitWeights ? 0 : model.biasOffset(l);
        }

    protected:
        Model model;
        bool splitWeights;
        std::vector<cl::Buffer> kernels{};
        std::vector<cl::Buffer> biases{};
    };

    template<typename Model>
    class OpenCLProcessor;
}

template<>
class ac::core::opencl::OpenCLProcessor<ac::core::model::ACNet> : public OpenCLProcessorSeqCNN<model::ACNet>
{
public:
    OpenCLProcessor(int device, const model::ACNet& model) noexcept;
    ~OpenCLProcessor() noexcept override;

private:
    void process(const Image& src, Image& dst) override;

private:
    util::ThreadLocal<cl::Kernel> conv3x3_1to8_relu_kernels{};
    util::ThreadLocal<cl::Kernel> conv3x3_8to8_relu_kernels{};
    util::ThreadLocal<cl::Kernel> deconv2x2_8to1_kernels{};

    util::ThreadLocal<ImageBuffer> inImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp1ImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp2ImageBuffers{};
    util::ThreadLocal<ImageBuffer> outImageBuffers{};
};

ac::core::opencl::OpenCLProcessor<ac::core::model::ACNet>::OpenCLProcessor(const int device, const model::ACNet& model) noexcept : OpenCLProcessorSeqCNN(device, model, kernel::ACNetKernelString) {}
ac::core::opencl::OpenCLProcessor<ac::core::model::ACNet>::~OpenCLProcessor() noexcept = default;

void ac::core::opencl::OpenCLProcessor<ac::core::model::ACNet>::process(const Image& src, Image& dst)
{
    cl::size_type srcW = src.width(), srcH = src.height();
    cl::size_type dstW = dst.width(), dstH = dst.height();
    cl::size_type srcRangeW = align(srcW, WorkGroupSize::x), srcRangeH = align(srcH, WorkGroupSize::y);
    cl::size_type dstRangeW = align(dstW, WorkGroupSize::x), dstRangeH = align(dstH, WorkGroupSize::y);

    auto& err = errors.local();
    auto& cmdq = queues.local(context.ctx, context.device, 0, &err); if (err != CL_SUCCESS) return;

    auto& conv3x3_1to8_relu = conv3x3_1to8_relu_kernels.local(context.program, "conv3x3_1to8_relu", &err); if (err != CL_SUCCESS) return;
    auto& conv3x3_8to8_relu = conv3x3_8to8_relu_kernels.local(context.program, "conv3x3_8to8_relu", &err); if (err != CL_SUCCESS) return;
    auto& deconv2x2_8to1 = deconv2x2_8to1_kernels.local(context.program, "deconv2x2_8to1", &err); if (err != CL_SUCCESS) return;

    auto& inImageBuffer = inImageBuffers.local();
    auto& tmp1ImageBuffer = tmp1ImageBuffers.local();
    auto& tmp2ImageBuffer = tmp2ImageBuffers.local();
    auto& outImageBuffer = outImageBuffers.local();

    auto& in = inImageBuffer.get(context.ctx, CL_MEM_READ_ONLY | CL_MEM_HOST_WRITE_ONLY, CL_R, channelType(src.type()), 1, srcW, srcH, &err); if (err != CL_SUCCESS) return;
    auto& tmp1 = tmp1ImageBuffer.get(context.ctx, CL_MEM_READ_WRITE, CL_RGBA, CL_HALF_FLOAT, 8, srcW, srcH, &err); if (err != CL_SUCCESS) return;
    auto& tmp2 = tmp2ImageBuffer.get(context.ctx, CL_MEM_READ_WRITE, CL_RGBA, CL_HALF_FLOAT, 8, srcW, srcH, &err); if (err != CL_SUCCESS) return;
    auto& out = outImageBuffer.get(context.ctx, CL_MEM_WRITE_ONLY | CL_MEM_HOST_READ_ONLY, CL_R, channelType(dst.type()), 1, dstW, dstH, &err); if (err != CL_SUCCESS) return;

    int l = 0;
    err = cmdq.enqueueWriteImage(in, CL_FALSE, { 0,0,0 }, { srcW,srcH,1 }, src.stride(), 0, src.ptr()); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_relu.setArg(0, in); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_relu.setArg(1, tmp1); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_relu.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_relu.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_relu.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_relu.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
    err = cmdq.enqueueNDRangeKernel(conv3x3_1to8_relu, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;
    for (int i = 0; i < 4; i++)
    {
        err = conv3x3_8to8_relu.setArg(0, tmp1); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_relu.setArg(1, tmp2); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_relu.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_relu.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_relu.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_relu.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
        err = cmdq.enqueueNDRangeKernel(conv3x3_8to8_relu, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;

        err = conv3x3_8to8_relu.setArg(0, tmp2); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_relu.setArg(1, tmp1); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_relu.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_relu.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_relu.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_relu.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
        err = cmdq.enqueueNDRangeKernel(conv3x3_8to8_relu, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;
    }
    err = deconv2x2_8to1.setArg(0, tmp1); if (err != CL_SUCCESS) return;
    err = deconv2x2_8to1.setArg(1, out); if (err != CL_SUCCESS) return;
    err = deconv2x2_8to1.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
    err = deconv2x2_8to1.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
    err = cmdq.enqueueNDRangeKernel(deconv2x2_8to1, cl::NullRange, { dstRangeW, dstRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return;
    err = cmdq.enqueueReadImage(out, CL_TRUE, { 0,0,0 }, { dstW,dstH,1 }, dst.stride(), 0, dst.ptr());
}

template<>
AC_CORE_EXPORT std::shared_ptr<ac::core::Processor> ac::core::Processor::create<ac::core::Processor::OpenCL, ac::core::model::ACNet>(const int idx, const model::ACNet& model)
{
    return std::make_shared<opencl::OpenCLProcessor<model::ACNet>>(idx, model);
}


template<>
class ac::core::opencl::OpenCLProcessor<ac::core::model::ARNet> : public OpenCLProcessorSeqCNN<model::ARNet>
{
public:
    OpenCLProcessor(int device, const model::ARNet& model) noexcept;
    ~OpenCLProcessor() noexcept override;

private:
    void process(const Image& src, Image& dst) override;

private:
    util::ThreadLocal<cl::Kernel> conv3x3_1to8_identity_kernels{};
    util::ThreadLocal<cl::Kernel> conv3x3_8to8_lrelu_kernels{};
    util::ThreadLocal<cl::Kernel> conv3x3_8to8_residual_identity_kernels{};
    util::ThreadLocal<cl::Kernel> conv3x3_8to8_residual_add_identity_kernels{};
    util::ThreadLocal<cl::Kernel> conv3x3_8to4_identity_pixelshuffle_4to1_kernels{};

    util::ThreadLocal<ImageBuffer> inImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp1ImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp2ImageBuffers{};
    util::ThreadLocal<ImageBuffer> tmp3ImageBuffers{};
    util::ThreadLocal<ImageBuffer> featImageBuffers{};
    util::ThreadLocal<ImageBuffer> outImageBuffers{};
};

ac::core::opencl::OpenCLProcessor<ac::core::model::ARNet>::OpenCLProcessor(const int device, const model::ARNet& model) noexcept : OpenCLProcessorSeqCNN(device, model, kernel::ARNetKernelString) {}
ac::core::opencl::OpenCLProcessor<ac::core::model::ARNet>::~OpenCLProcessor() noexcept = default;

void ac::core::opencl::OpenCLProcessor<ac::core::model::ARNet>::process(const Image& src, Image& dst)
{
    cl::size_type srcW = src.width(), srcH = src.height();
    cl::size_type dstW = dst.width(), dstH = dst.height();
    cl::size_type srcRangeW = align(srcW, WorkGroupSize::x), srcRangeH = align(srcH, WorkGroupSize::y);

    auto& err = errors.local();
    auto& cmdq = queues.local(context.ctx, context.device, 0, &err); if (err != CL_SUCCESS) return;

    auto& conv3x3_1to8_identity = conv3x3_1to8_identity_kernels.local(context.program, "conv3x3_1to8_identity", &err); if (err != CL_SUCCESS) return;
    auto& conv3x3_8to8_lrelu = conv3x3_8to8_lrelu_kernels.local(context.program, "conv3x3_8to8_lrelu", &err); if (err != CL_SUCCESS) return;
    auto& conv3x3_8to8_residual_identity = conv3x3_8to8_residual_identity_kernels.local(context.program, "conv3x3_8to8_residual_identity", &err); if (err != CL_SUCCESS) return;
    auto& conv3x3_8to8_residual_add_identity = conv3x3_8to8_residual_add_identity_kernels.local(context.program, "conv3x3_8to8_residual_add_identity", &err); if (err != CL_SUCCESS) return;
    auto& conv3x3_8to4_identity_pixelshuffle_4to1 = conv3x3_8to4_identity_pixelshuffle_4to1_kernels.local(context.program, "conv3x3_8to4_identity_pixelshuffle_4to1", &err); if (err != CL_SUCCESS) return;

    auto& inImageBuffer = inImageBuffers.local();
    auto& tmp1ImageBuffer = tmp1ImageBuffers.local();
    auto& tmp2ImageBuffer = tmp2ImageBuffers.local();
    auto& tmp3ImageBuffer = tmp3ImageBuffers.local();
    auto& featImageBuffer = featImageBuffers.local();
    auto& outImageBuffer = outImageBuffers.local();

    auto& in = inImageBuffer.get(context.ctx, CL_MEM_READ_ONLY | CL_MEM_HOST_WRITE_ONLY, CL_R, channelType(src.type()), 1, srcW, srcH, &err); if (err != CL_SUCCESS) return;
    auto& tmp1 = tmp1ImageBuffer.get(context.ctx, CL_MEM_READ_WRITE, CL_RGBA, CL_HALF_FLOAT, 8, srcW, srcH, &err); if (err != CL_SUCCESS) return;
    auto& tmp2 = tmp2ImageBuffer.get(context.ctx, CL_MEM_READ_WRITE, CL_RGBA, CL_HALF_FLOAT, 8, srcW, srcH, &err); if (err != CL_SUCCESS) return;
    auto& tmp3 = tmp3ImageBuffer.get(context.ctx, CL_MEM_READ_WRITE, CL_RGBA, CL_HALF_FLOAT, 8, srcW, srcH, &err); if (err != CL_SUCCESS) return;
    auto& feat = featImageBuffer.get(context.ctx, CL_MEM_READ_WRITE, CL_RGBA, CL_HALF_FLOAT, 8, srcW, srcH, &err); if (err != CL_SUCCESS) return;
    auto& out = outImageBuffer.get(context.ctx, CL_MEM_WRITE_ONLY | CL_MEM_HOST_READ_ONLY, CL_R, channelType(dst.type()), 1, dstW, dstH, &err); if (err != CL_SUCCESS) return;

    int l = 0;
    err = cmdq.enqueueWriteImage(in, CL_FALSE, { 0,0,0 }, { srcW,srcH,1 }, src.stride(), 0, src.ptr()); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_identity.setArg(0, in); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_identity.setArg(1, feat); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_identity.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_identity.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_identity.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_1to8_identity.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
    err = cmdq.enqueueNDRangeKernel(conv3x3_1to8_identity, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;

    err = conv3x3_8to8_lrelu.setArg(0, feat); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(1, tmp1); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(6, 0.2f); if (err != CL_SUCCESS) return;
    err = cmdq.enqueueNDRangeKernel(conv3x3_8to8_lrelu, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;

    err = conv3x3_8to8_residual_identity.setArg(0, tmp1); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_identity.setArg(1, tmp2); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_identity.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_identity.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_identity.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_identity.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_identity.setArg(6, feat); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_identity.setArg(7, 0.2f); if (err != CL_SUCCESS) return;
    err = cmdq.enqueueNDRangeKernel(conv3x3_8to8_residual_identity, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;

    for (int i = 0; i < (model.blocks() - 2) / 2; i++)
    {
        err = conv3x3_8to8_lrelu.setArg(0, tmp2); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(1, tmp1); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(6, 0.2f); if (err != CL_SUCCESS) return;
        err = cmdq.enqueueNDRangeKernel(conv3x3_8to8_lrelu, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;

        err = conv3x3_8to8_residual_identity.setArg(0, tmp1); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(1, tmp3); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(6, tmp2); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(7, 0.2f); if (err != CL_SUCCESS) return;
        err = cmdq.enqueueNDRangeKernel(conv3x3_8to8_residual_identity, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;

        err = conv3x3_8to8_lrelu.setArg(0, tmp3); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(1, tmp1); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_lrelu.setArg(6, 0.2f); if (err != CL_SUCCESS) return;
        err = cmdq.enqueueNDRangeKernel(conv3x3_8to8_lrelu, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;

        err = conv3x3_8to8_residual_identity.setArg(0, tmp1); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(1, tmp2); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(6, tmp3); if (err != CL_SUCCESS) return;
        err = conv3x3_8to8_residual_identity.setArg(7, 0.2f); if (err != CL_SUCCESS) return;
        err = cmdq.enqueueNDRangeKernel(conv3x3_8to8_residual_identity, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;
    }
    err = conv3x3_8to8_lrelu.setArg(0, tmp2); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(1, tmp1); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_lrelu.setArg(6, 0.2f); if (err != CL_SUCCESS) return;
    err = cmdq.enqueueNDRangeKernel(conv3x3_8to8_lrelu, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;

    err = conv3x3_8to8_residual_add_identity.setArg(0, tmp1); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_add_identity.setArg(1, tmp3); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_add_identity.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_add_identity.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_add_identity.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_add_identity.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_add_identity.setArg(6, tmp2); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_add_identity.setArg(7, 0.2f); if (err != CL_SUCCESS) return;
    err = conv3x3_8to8_residual_add_identity.setArg(8, feat); if (err != CL_SUCCESS) return;
    err = cmdq.enqueueNDRangeKernel(conv3x3_8to8_residual_add_identity, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return; l++;

    err = conv3x3_8to4_identity_pixelshuffle_4to1.setArg(0, tmp3); if (err != CL_SUCCESS) return;
    err = conv3x3_8to4_identity_pixelshuffle_4to1.setArg(1, out); if (err != CL_SUCCESS) return;
    err = conv3x3_8to4_identity_pixelshuffle_4to1.setArg(2, kernel(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to4_identity_pixelshuffle_4to1.setArg(3, kernelOffset(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to4_identity_pixelshuffle_4to1.setArg(4, bias(l)); if (err != CL_SUCCESS) return;
    err = conv3x3_8to4_identity_pixelshuffle_4to1.setArg(5, biasOffset(l)); if (err != CL_SUCCESS) return;
    err = cmdq.enqueueNDRangeKernel(conv3x3_8to4_identity_pixelshuffle_4to1, cl::NullRange, { srcRangeW, srcRangeH }, { WorkGroupSize::x, WorkGroupSize::y }); if (err != CL_SUCCESS) return;
    err = cmdq.enqueueReadImage(out, CL_TRUE, { 0,0,0 }, { dstW,dstH,1 }, dst.stride(), 0, dst.ptr());
}

template<>
AC_CORE_EXPORT std::shared_ptr<ac::core::Processor> ac::core::Processor::create<ac::core::Processor::OpenCL, ac::core::model::ARNet>(const int idx, const model::ARNet& model)
{
    return std::make_shared<opencl::OpenCLProcessor<model::ARNet>>(idx, model);
}


template<>
AC_CORE_EXPORT const char* ac::core::Processor::info<ac::core::Processor::OpenCL>()
{
    static auto infoBuffer = []() -> std::string {
        auto contextList = opencl::getContextList();
        std::ostringstream buffer{ "OpenCL:\n", std::ios_base::ate };
        for (std::size_t i = 0; i < contextList.size(); i++)
            buffer << "  [" << i << "] " << contextList[i].name << " (" << contextList[i].info << ") " << '\n';
        return buffer.str();
    }();
    return infoBuffer.c_str();
}
