#ifndef AC_BINDING_C_CORE_IMAGE_H
#define AC_BINDING_C_CORE_IMAGE_H

#include <stdint.h>
#include <stddef.h>

#include "ACCExport.h" // Generated by CMake

#ifdef __cplusplus
#   define AC_C_API extern "C" AC_C_EXPORT
#else
#   define AC_C_API AC_C_EXPORT
#endif

enum ACImageElementType
{
    AC_IMAGE_UINT8   = 0 << 8 | 1,
    AC_IMAGE_UINT16  = 0 << 8 | 2,
    AC_IMAGE_FLOAT32 = 2 << 8 | 4
};

enum ACImreadModes
{
    AC_IMREAD_UNCHANGED = 0,
    AC_IMREAD_GRAYSCALE = 1,
    AC_IMREAD_COLOR     = 3,
    AC_IMREAD_RGB       = 3,
    AC_IMREAD_RGBA      = 4,
};

enum ACResizeModes
{
    AC_RESIZE_POINT,
    AC_RESIZE_CATMULL_ROM,
    AC_RESIZE_MITCHELL_NETRAVALI,
    AC_RESIZE_BICUBIC_0_60,
    AC_RESIZE_BICUBIC_0_75,
    AC_RESIZE_BICUBIC_0_100,
    AC_RESIZE_BICUBIC_20_50,
    AC_RESIZE_SOFTCUBIC50,
    AC_RESIZE_SOFTCUBIC75,
    AC_RESIZE_SOFTCUBIC100,
    AC_RESIZE_LANCZOS2,
    AC_RESIZE_LANCZOS3,
    AC_RESIZE_LANCZOS4,
    AC_RESIZE_SPLINE16,
    AC_RESIZE_SPLINE36,
    AC_RESIZE_SPLINE64,
    AC_RESIZE_BILINEAR,
};

typedef struct ACImage
{
    int width;
    int height;
    int channels;
    int stride;
    int element_type;
    void* ptr;
    struct ACImageHandle* hptr;
} ACImage;

AC_C_API ACImage* ac_image_alloc(void);
AC_C_API void ac_image_free(ACImage** image);
AC_C_API int ac_image_ref(const ACImage* src, ACImage* dst);
AC_C_API void ac_image_unref(ACImage* image);
AC_C_API int ac_image_create(ACImage* image);
AC_C_API int ac_image_map(ACImage* image);
AC_C_API int ac_image_from(ACImage* image, const void* data);
AC_C_API int ac_image_view(const ACImage* src, ACImage* dst, int x, int y, int w, int h);
AC_C_API int ac_image_clone(const ACImage* src, ACImage* dst);
AC_C_API int ac_image_to(const ACImage* image, void* data, int stride);

#ifndef AC_CORE_DISABLE_IMAGE_IO
AC_C_API int ac_imread(const char* filename, int mode, ACImage* image);
AC_C_API int ac_imwrite(const char* filename, const ACImage* image);
#endif

AC_C_API int ac_resize(const ACImage* src, ACImage* dst, double fx, double fy, int mode);
AC_C_API int ac_rgb2yuv(const ACImage* rgb, ACImage* yuv);
AC_C_API int ac_rgba2yuva(const ACImage* rgba, ACImage* yuva);
AC_C_API int ac_yuv2rgb(const ACImage* yuv, ACImage* rgb);
AC_C_API int ac_yuva2rgba(const ACImage* yuva, ACImage* rgba);

static int ac_image_size(const ACImage* image)
{
    return image->height * image->stride;
}
static int ac_image_element_size(const ACImage* image)
{
    return image->element_type & 0xff;
}
static int ac_image_pixel_size(const ACImage* image)
{
    return image->channels * ac_image_element_size(image);
}
static uint8_t* ac_image_data(const ACImage* image)
{
    return (uint8_t*)image->ptr;
}
static uint8_t* ac_image_line(const ACImage* image, int y)
{
    return ac_image_data(image) + image->stride * y;
}
static uint8_t* ac_image_pixel(const ACImage* image, int x, int y)
{
    return ac_image_line(image, y) + x * ac_image_pixel_size(image);
}
static int ac_image_empty(const ACImage* image)
{
    return image->ptr == NULL;
}
static int ac_image_is_uint(const ACImage* image)
{
    return (image->element_type >> 8) == 0;
}
static int ac_image_is_int(const ACImage* image)
{
    return (image->element_type >> 8) == 1;
}
static int ac_image_is_float(const ACImage* image)
{
    return (image->element_type >> 8) == 2;
}

#endif
