function(minifier_opencl_kernel SRC_VAR DST_VAR)
    string(REGEX REPLACE "//[^\n]*" "" TMP "${${SRC_VAR}}")
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" TMP "${TMP}")
    string(REGEX REPLACE "[ \t]+" " " TMP "${TMP}")
    string(REGEX REPLACE "\n[ \t]+" "\n" TMP "${TMP}")
    string(REGEX REPLACE "[ \t]+\n" "\n" TMP "${TMP}")
    string(REGEX REPLACE "\n+" "\n" TMP "${TMP}")
    string(REGEX REPLACE "\\(\n" "(" TMP "${TMP}")
    string(REGEX REPLACE "\n\\)" ")" TMP "${TMP}")
    string(REGEX REPLACE "{\n" "{" TMP "${TMP}")
    string(REGEX REPLACE "\\)\n{" "){" TMP "${TMP}")
    string(REGEX REPLACE "[ \t]*,[ \t\r\n]+" "," TMP "${TMP}")
    string(REGEX REPLACE "[ \t]+\\+[ \t\r\n]+" "+" TMP "${TMP}")
    string(REGEX REPLACE "[ \t]+-[ \t\r\n]+" "-" TMP "${TMP}")
    string(REGEX REPLACE "[ \t]+=[ \t\r\n]+" "=" TMP "${TMP}")

    set(${DST_VAR} "${TMP}" PARENT_SCOPE)
endfunction()
